### ISSUE TITLE
Package path not exported error - error when running react-native rnx-start

### ISSUE THREAD

**Issue by simarmol** [microsoft/rnx-kit#1227]
### What happened?

Trying to set up an existing project to work with rnx-kit. I am getting errors from the metro server when I run `yarn react-native rnx-start --reset-cache`. I have no problem whatsoever when I run `yarn react-native start --reset-cache`.

The errors look like this:

```
error: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /REPO//node_modules/node-html-parser/package.json
    at new NodeError (node:internal/errors:371:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:453:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:729:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at /REPO/node_modules/@rnx-kit/tools-react-native/lib/platform.js:77:46
    at Array.forEach (<anonymous>)
    at getAvailablePlatformsUncached (/repo/node_modules/@rnx-kit/tools-react-native/lib/platform.js:76:7)
```

I'm currently getting it for 'node-html-parser'. I was also getting the same error for a local package devDependency before, which is only configured to compile an ESM module. I removed it temporarily but immediately ran into the same error in node-html-parser. 

I'm assuming it's an esm vs. Common module thing? Which would make sense, except that the normal 'react-native start' command is working fine.

I'm also getting this warning about the blocklist, but I'm unsure if it is related.
```
● Deprecation Warning:

Warning: Metro config option `blacklistRE` is deprecated.
         Please use `blockList` instead.

● Validation Warning:

  Unknown option "blockList" with value 
  ```

I'd like some help getting it working for rnx-start if possible.  I'm not sure if I missed a config option somewhere, but I've tried various minor permutations of configs to no avail.

After looking around existing issues, I think this may be related to #805 or #1046.

### Affected Package

@rnx-kit/metro-config

### Version

 1.2.29

### Which platforms are you seeing this issue on?

- [X] Android
- [X] iOS
- [ ] macOS
- [ ] Windows

### System Information

```true
info Fetching system and libraries information...
System:
    OS: macOS 12.2.1
    CPU: (8) arm64 Apple M1
    Memory: 77.95 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 1.22.17 - ~/.yarn/bin/yarn
    npm: 6.14.15 - ~/_/REPO/node_modules/.bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.2 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 23, 27, 28, 29, 30
      Build Tools: 29.0.2, 29.0.3, 30.0.2, 31.0.0
      System Images: android-30 | Google APIs ARM 64 v8a, android-31 | Google APIs ARM 64 v8a
      Android NDK: 22.1.7171670
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7784292
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.14 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.65.1 => 0.65.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to Reproduce

Unfortunately this is in a very large work repo. I can paste relevant snippets? I cobbled together the config files from what I had before in the repository with what was in the /test-app package.json in the rnx-kit repo.

I left the rn-cli.config.js file pretty empty except one line I copied over from the old version I had, because I couldn't find documentation on it and the order of precedence between the rn-cli and metro config files. Adding the command line flags for rnx-kit and the rnx-kit fields in pacakge.json, I had no idea what would be applied first so I just tried to keep everything in metro.config.

relevant package.json bits
```json
{
  "dependencies": {
    "react": "17.0.2",
    "react-dom": "^17.0.2",
    "react-native": "0.65.1"
}, 
 { 
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/eslint-parser": "^7.17.0",
    "@babel/runtime": "^7.12.5",
    "@rnx-kit/cli": "^0.11.1",
    "@rnx-kit/metro-config": "^1.2.29",
    "@rnx-kit/metro-plugin-cyclic-dependencies-detector": "^1.0.21",
    "@rnx-kit/metro-plugin-duplicates-checker": "^1.2.15",
    "@rnx-kit/metro-resolver-symlinks": "^0.1.16"
},
 "rnx-kit": {
    "reactNativeVersion": "^0.65",
    "kitType": "app",
    "capabilities": [
      "animation",
      "babel-preset-react-native",
      "core",
      "core-android",
      "core-ios",
      "datetime-picker",
      "filesystem",
      "gestures",
      "hermes",
      "jest",
      "modal",
      "navigation/native",
      "netinfo",
      "react",
      "react-dom",
      "react-test-renderer",
      "screens",
      "svg",
      "webview"
    ]
  }
}

```
metro.config.js

```javascript
const defaultSourceExts = require("metro-config/src/defaults/defaults").sourceExts;
const { exclusionList, makeMetroConfig } = require("@rnx-kit/metro-config");
const MetroSymlinksResolver = require("@rnx-kit/metro-resolver-symlinks");

const blockList = exclusionList([
  /node_modules\/node-html-parser\/package\.json/, // this didn't seem to make a difference
  /react-native\/local-cli\/core\/__fixtures__.*/,
  /node_modules\/.*\/node_modules\/react-native\/.*/,
  /.yalc\/.*\/package\.json/,
]);

module.exports = makeMetroConfig({
  projectRoot: __dirname,
  resolver: {
    sourceExts: process.env.RN_SRC_EXT
      ? process.env.RN_SRC_EXT.split(",").concat(defaultSourceExts)
      : defaultSourceExts,
  },
  blacklistRE: blockList,
  blockList,
});

```

rn-cli.config.js
```javascript
module.exports = {
  getAssetExts() {
    return ["jsx"];
  }
```

babel.config.js
```javascript
module.exports = {
  presets: ["module:metro-react-native-babel-preset"],
};

```
Will try to make a minimal repro project later if necessary.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tido64** [comment]
Thanks for the super detailed issue description! I found the bug, and have a fix ready (I just need to add some more tests).
