### ISSUE TITLE
Package subpath './package.json' is not defined by "exports" when using @rnx-kit/metro-resolver-symlinks

### ISSUE THREAD

**Issue by nutstick** [microsoft/rnx-kit#1469]
### What happened?

 I am getting errors from the metro server after trying to integrate with `@rnx-kit/metro-resolver-symlinks`

```
error: Error: Unable to resolve module telejson from /repro-rnx-metro-symlink-exports/packages/utils/src/index.js: telejson could not be found within the project or in these directories:
  ../packages/utils/node_modules
  ../node_modules
  ../../../node_modules
```

After some debugging, I found that the package `telejson` uses `exports` fields in package.json

```
{
  "name": "telejson",
  "version": "5.3.3",
  ...
  "exports": {
    "import": "./dist/esm/index.js",
    "require": "./dist/cjs/index.js"
  },
}
```

And since @rnx-kit/metro-resolver-symlinks using `require.resolve('${pkgName}/package.json')` https://github.com/microsoft/rnx-kit/blob/master/packages/metro-resolver-symlinks/src/resolver.ts#L60. It unable to resolve to correct package

This is the error throw from `resolveFrom`
```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /Users/nuttapat.kirawittaya/Projects/repro-rnx-metro-symlink-exports/packages/utils/node_modules/telejson/package.json
    at new NodeError (internal/errors.js:322:7)
    at throwExportsNotFound (internal/modules/esm/resolve.js:332:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:565:3)
    at resolveExports (internal/modules/cjs/loader.js:450:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:490:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:888:27)
    at Function.resolve (internal/modules/cjs/helpers.js:107:19)
    at resolveFrom (/Users/nuttapat.kirawittaya/Projects/repro-rnx-metro-symlink-exports/node_modules/.pnpm/@rnx-kit+metro-resolver-symlinks@0.1.16/node_modules/@rnx-kit/metro-resolver-symlinks/lib/resolver.js:27:20)
    at resolveModulePath (/Users/nuttapat.kirawittaya/Projects/repro-rnx-metro-symlink-exports/node_modules/.pnpm/@rnx-kit+metro-resolver-symlinks@0.1.16/node_modules/@rnx-kit/metro-resolver-symlinks/lib/resolver.js:67:32)
    at /Users/nuttapat.kirawittaya/Projects/repro-rnx-metro-symlink-exports/node_modules/.pnpm/@rnx-kit+metro-resolver-symlinks@0.1.16/node_modules/@rnx-kit/metro-resolver-symlinks/lib/index.js:14:78 {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

### Affected Package

@rnx-kit/metro-resolver-symlinks

### Version

0.1.16

### Which platforms are you seeing this issue on?

- [X] Android
- [X] iOS
- [X] macOS
- [X] Windows

### System Information

```true
info Fetching system and libraries information...
System:
    OS: macOS 11.6.5
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 2.48 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.19.1 - /usr/local/opt/node@14/bin/node
    Yarn: 1.22.18 - ~/.yarn/bin/yarn
    npm: 6.14.16 - /usr/local/opt/node@14/bin/npm
    Watchman: 2022.03.21.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.2 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7583922
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.10 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.1 => 0.68.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

PNPM Version: 6.32.11
```

### Steps to Reproduce

Here is a reproducible repro https://github.com/nutstick/repro-rnx-metro-symlink-exports, can follow steps in README

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nutstick** [comment]
I realize it pretty similar to https://github.com/microsoft/rnx-kit/issues/1227. Not sure it's fixed yet

**Comment by tido64** [comment]
Thanks for reporting this! I've just submitted PR to fix this package. Will be going through all our packages to ensure we don't do this elsewhere.
