### ISSUE TITLE
Starting metro does not take browser in account

### ISSUE THREAD

**Issue by billouboq** [microsoft/rnx-kit#1548]
### What happened?

Hello !

Just started my app with the new cli with react-native start but it failed for engine.io-client dependancy which has a browser attribute in package.json. It seems old metro was moving path correctly but new config does not :

Error in metro :

```
  3 |  */
  4 |
> 5 | var XMLHttpRequest = require('xmlhttprequest-ssl');
    |                               ^
  6 | var XHR = require('./polling-xhr');
  7 | var JSONP = require('./polling-jsonp');
  8 | var websocket = require('./websocket');
    at ModuleResolver.resolveDependency (/Users/aurelienboquet/beedeez/beedeez-main/packages/beedeez-app-prepro/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:129:15)
    at DependencyGraph.resolveDependency (/Users/aurelienboquet/beedeez/beedeez-main/packages/beedeez-app-prepro/node_modules/metro/src/node-haste/DependencyGraph.js:288:43)
    at Object.resolve (/Users/aurelienboquet/beedeez/beedeez-main/packages/beedeez-app-prepro/node_modules/metro/src/lib/transformHelpers.js:129:24)
    at resolve (/Users/aurelienboquet/beedeez/beedeez-main/packages/beedeez-app-prepro/node_modules/metro/src/DeltaBundler/traverseDependencies.js:396:33)
    at /Users/aurelienboquet/beedeez/beedeez-main/packages/beedeez-app-prepro/node_modules/metro/src/DeltaBundler/traverseDependencies.js:412:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (/Users/aurelienboquet/beedeez/beedeez-main/packages/beedeez-app-prepro/node_modules/metro/src/DeltaBundler/traverseDependencies.js:411:33)
    at processModule (/Users/aurelienboquet/beedeez/beedeez-main/packages/beedeez-app-prepro/node_modules/metro/src/DeltaBundler/traverseDependencies.js:140:31)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
 BUNDLE  ./index.js 

error: Error: Unable to resolve module xmlhttprequest-ssl from /Users/aurelienboquet/beedeez/beedeez-main/packages/beedeez-app-prepro/node_modules/engine.io-client/lib/transports/index.js: xmlhttprequest-ssl could not be found within the project or in these directories:
  node_modules/engine.io-client/node_modules
  node_modules
  ../../node_modules
  ../../../../node_modules
```

Engine.io-client package.json :

```json
{
  "name": "engine.io-client",
  "description": "Client for the realtime Engine",
  "license": "MIT",
  "version": "3.4.4",
  "main": "lib/index.js",
  "homepage": "https://github.com/socketio/engine.io-client",
  "contributors": [
    {
      "name": "Guillermo Rauch",
      "email": "rauchg@gmail.com"
    },
    {
      "name": "Vladimir Dronnikov",
      "email": "dronnikov@gmail.com"
    },
    {
      "name": "Christoph Dorn",
      "web": "https://github.com/cadorn"
    },
    {
      "name": "Mark Mokryn",
      "email": "mokesmokes@gmail.com"
    }
  ],
  "dependencies": {
    "component-emitter": "~1.3.0",
    "component-inherit": "0.0.3",
    "debug": "~3.1.0",
    "engine.io-parser": "~2.2.0",
    "has-cors": "1.1.0",
    "indexof": "0.0.1",
    "parseqs": "0.0.6",
    "parseuri": "0.0.6",
    "ws": "~6.1.0",
    "xmlhttprequest-ssl": "~1.5.4",
    "yeast": "0.1.2"
  },
  "devDependencies": {
    "babel-core": "^6.24.0",
    "babel-eslint": "4.1.7",
    "babel-loader": "^6.4.1",
    "babel-preset-es2015": "^6.24.0",
    "blob": "^0.0.4",
    "concat-stream": "^1.6.0",
    "del": "^2.2.2",
    "derequire": "^2.0.6",
    "engine.io": "3.4.0",
    "eslint-config-standard": "4.4.0",
    "eslint-plugin-standard": "1.3.1",
    "expect.js": "^0.3.1",
    "express": "4.15.2",
    "gulp": "3.9.1",
    "gulp-eslint": "1.1.1",
    "gulp-file": "^0.3.0",
    "gulp-istanbul": "^1.1.1",
    "gulp-mocha": "^4.3.0",
    "gulp-task-listing": "1.0.1",
    "istanbul": "^0.4.5",
    "mocha": "^3.2.0",
    "webpack": "1.12.12",
    "webpack-stream": "^3.2.0",
    "zuul": "3.11.1",
    "zuul-builder-webpack": "^1.2.0",
    "zuul-ngrok": "4.0.0"
  },
  "scripts": {
    "test": "gulp test"
  },
  "browser": {
    "ws": false,
    "xmlhttprequest-ssl": "./lib/xmlhttprequest.js",
    "./lib/globalThis.js": "./lib/globalThis.browser.js"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/socketio/engine.io-client.git"
  },
  "files": [
    "index.js",
    "lib/",
    "engine.io.js"
  ]
}
```

We can see in browser attribute that it should use "./lib/xmlhttprequest.js" path, which it does not now with new @rnk metro configuration.

My Rnx configuration :

```json
	"rnx-kit": {
		"bundle": true,
		"targets": [
			"ios",
			"android"
		]
	}
```

### Affected Package

@rnx-kit/cli

### Version

0.12.7

### Which platforms are you seeing this issue on?

- [X] Android
- [X] iOS
- [ ] macOS
- [ ] Windows

### System Information

```true
System:
    OS: macOS 11.6.2
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
    Memory: 1.17 GB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.22.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.11 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.2 - /Users/aurelienboquet/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 21, 22, 23, 24, 25, 26, 27, 28, 29, 30
      Build Tools: 27.0.2, 27.0.3, 28.0.0, 28.0.1, 28.0.2, 28.0.3, 29.0.0, 29.0.1, 29.0.2, 29.0.3, 30.0.0, 30.0.1, 30.0.2
      System Images: android-28 | Google Play Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6514223
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_265 - /Users/aurelienboquet/.jenv/shims/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.66.3 => 0.66.3 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to Reproduce

- Install engine.io-client version
- run start

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tido64** [comment]
Hi @billouboq, thanks for filing this issue. What does your `metro.config.js` look like? Do you have `resolveRequest` set to anything? If you're using our symlinks resolver, it seems like we missed the special handling of the `browser` field.

**Comment by billouboq** [comment]
Hello Tido, I'm using the default metro config exemple from @rnx-kit getting started so that may be it

**Comment by tido64** [comment]
Sorry this took so long to get to. I think this should be fixed in the PR above. It would be great if you could test it as well.

**Comment by billouboq** [comment]
Hello !

Will try as soon as possible but might not be today.
Thanks 🙏

**Comment by billouboq** [comment]
This does resolve the issue, thank you very much ! 🙏
