### ISSUE TITLE
rnx-kit bundler breaks when react-hook-form is imported in the project

### ISSUE THREAD

**Issue by Thanaen** [microsoft/rnx-kit#1566]
### What happened?

Hello,

When using rnx-kit as a bundler, we encounter an error as soon as the "react-hook-form" package is imported into the project.

It seemed more relevant to me to create an issue here first, since this is a rather special setup and react-hook-form may not be the culprit here (to be verified 😁)

Here's the error we encounter: 
```
error: Error: While trying to resolve module `react-hook-form` from file `C:\Dev\Repros\RnxKitRHF\App.js`, the package `C:\Dev\Repros\RnxKitRHF\node_modules\react-hook-form\package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`C:\Dev\Repros\RnxKitRHF\node_modules\react-hook-form\dist\index.esm.mjs`. Indeed, none of these files exist:

  * C:\Dev\Repros\RnxKitRHF\node_modules\react-hook-form\dist\index.esm.mjs(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * C:\Dev\Repros\RnxKitRHF\node_modules\react-hook-form\dist\index.esm.mjs\index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
    at DependencyGraph.resolveDependency (C:\Dev\Repros\RnxKitRHF\node_modules\metro\src\node-haste\DependencyGraph.js:243:17)
    at Object.resolve (C:\Dev\Repros\RnxKitRHF\node_modules\metro\src\lib\transformHelpers.js:129:24)
    at resolve (C:\Dev\Repros\RnxKitRHF\node_modules\metro\src\DeltaBundler\traverseDependencies.js:396:33)
    at C:\Dev\Repros\RnxKitRHF\node_modules\metro\src\DeltaBundler\traverseDependencies.js:412:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (C:\Dev\Repros\RnxKitRHF\node_modules\metro\src\DeltaBundler\traverseDependencies.js:411:33)
    at processModule (C:\Dev\Repros\RnxKitRHF\node_modules\metro\src\DeltaBundler\traverseDependencies.js:140:31)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async addDependency (C:\Dev\Repros\RnxKitRHF\node_modules\metro\src\DeltaBundler\traverseDependencies.js:230:18)
    at async Promise.all (index 2)
jest-haste-map: watch error:
  Error: Cannot parse C:\Dev\Repros\RnxKitRHF\package.json as JSON: Unexpected token } in JSON at position 308
    at Object.worker (C:\Dev\Repros\RnxKitRHF\node_modules\metro\node_modules\jest-haste-map\build\worker.js:146:13)
    at HasteMap._processFile (C:\Dev\Repros\RnxKitRHF\node_modules\metro\node_modules\jest-haste-map\build\index.js:757:8)
    at C:\Dev\Repros\RnxKitRHF\node_modules\metro\node_modules\jest-haste-map\build\index.js:1104:34
```

### Affected Package

@rnx-kit/babel-preset-metro-react-native

### Version

1.1.0

### Which platforms are you seeing this issue on?

- [X] Android
- [ ] iOS
- [ ] macOS
- [X] Windows

### System Information

```true
System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz
    Memory: 11.86 GB / 31.61 GB
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.15 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD
    Watchman: 20220306.015012.0 - C:\Dev\Utils\watchman-v2022.03.07.00-windows\bin\watchman.EXE
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      Versions: 10.0.17763.0, 10.0.19041.0
  IDEs:
    Android Studio: AI-212.5712.43.2112.8512546
    Visual Studio: 17.2.32516.85 (Visual Studio Enterprise 2022), 16.11.32228.343 (Visual Studio Enterprise 2019)
  Languages:
    Java: 11.0.14.1 - C:\Program Files\Eclipse Adoptium\jdk-11.0.14.101-hotspot\bin\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.68.2 => 0.68.2
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to Reproduce

Clone this project: https://github.com/Thanaen/RnxKitRHF
Trigger the creation of a bundle (by running `yarn android` for example)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tido64** [comment]
By default, Metro just picks up `js`, `json`, `ts`, and `tsx` ([source](https://github.com/facebook/metro/blob/1ae8ab07bab292743fff1ed399d289b05529b0f6/packages/metro-config/src/defaults/defaults.js#L53)). If you want to include `mjs`, you need to manually add it to [`resolver.sourceExts`](https://facebook.github.io/metro/docs/configuration/#sourceexts) in your `metro.config.js`.

**Comment by Thanaen** [comment]
Ok, thank you!
I added this line in the metro config, and it did solve the problem. 😄

`sourceExts: ['js', 'jsx', 'ts', 'tsx', 'mjs']`
