### ISSUE TITLE
Metro crashes when using pnpm and `metro-resolver-symlinks`  with error: `Cannot find module 'metro-resolver'`

### ISSUE THREAD

**Issue by jbarzegar** [microsoft/rnx-kit#1581]
### What happened?

I was testing out using `@rnx-kit/metro-resolver-symlinks` with `pnpm 6`. After installing all relevant dependencies I attempted to start RN's dev server but it crashed with this error:

```
Cannot find module 'metro-resolver'. This probably means that '@rnx-kit/metro-resolver-symlinks' is not compatible with the version of 'metro' that you are currently using. Please update to the latest version and try again. If the issue still persists after the update, please file a bug at https://github.com/microsoft/rnx-kit/issues.
Error: Cannot find module 'metro-resolver'. This probably means that '@rnx-kit/metro-resolver-symlinks' is not compatible with the version of 'metro' that you are currently using. Please update to the latest version and try again. If the issue still persists after the update, please file a bug at https://github.com/microsoft/rnx-kit/issues.
    at getMetroResolver (/Users/james/Dev/jbarzegar/RnxKitTest/node_modules/.pnpm/@rnx-kit+metro-resolver-symlinks@0.1.19/node_modules/@rnx-kit/metro-resolver-symlinks/lib/resolver.js:50:15)
    at makeResolver (/Users/james/Dev/jbarzegar/RnxKitTest/node_modules/.pnpm/@rnx-kit+metro-resolver-symlinks@0.1.19/node_modules/@rnx-kit/metro-resolver-symlinks/lib/symlinkResolver.js:8:59)
    at Object.<anonymous> (/Users/james/Dev/jbarzegar/RnxKitTest/metro.config.js:14:21)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at module.exports (/Users/james/Dev/jbarzegar/RnxKitTest/node_modules/.pnpm/import-fresh@2.0.0/node_modules/import-fresh/index.js:28:9)
```

I installed the latest version of `metro`, `metro-core`, and `metro-resolver` however the error still persists.

Ran `pnpm exec rnx-dep-check` ran without issue but returned a slew of warnings about packages that could not be resolved:

```
warn Unable to resolve module 'loose-envify'
warn Unable to resolve module 'object-assign'
warn Unable to resolve module '@jest/create-cache-key-function'
warn Unable to resolve module '@react-native-community/cli'
warn Unable to resolve module '@react-native-community/cli-tools'
warn Unable to resolve module 'chalk'
warn Unable to resolve module 'execa'
warn Unable to resolve module 'fs-extra'
warn Unable to resolve module 'glob'
warn Unable to resolve module 'jetifier'
warn Unable to resolve module 'lodash'
warn Unable to resolve module 'logkitty'
warn Unable to resolve module 'slash'
warn Unable to resolve module 'js-yaml'
warn Unable to resolve module 'ora'
warn Unable to resolve module 'plist'
warn Unable to resolve module '@react-native/assets'
warn Unable to resolve module '@react-native/normalize-color'
warn Unable to resolve module '@react-native/polyfills'
warn Unable to resolve module 'abort-controller'
warn Unable to resolve module 'anser'
warn Unable to resolve module 'base64-js'
warn Unable to resolve module 'invariant'
warn Unable to resolve module 'react-is'
warn Unable to resolve module 'event-target-shim'
warn Unable to resolve module 'hermes-engine'
warn Unable to resolve module 'jsc-android'
warn Unable to resolve module 'metro-react-native-babel-transformer'
warn Unable to resolve module 'metro-runtime'
warn Unable to resolve module 'metro-source-map'
warn Unable to resolve module 'nullthrows'
warn Unable to resolve module 'pretty-format'
warn Unable to resolve module 'promise'
warn Unable to resolve module 'react-devtools-core'
warn Unable to resolve module 'react-native-gradle-plugin'
warn Unable to resolve module 'react-refresh'
warn Unable to resolve module 'react-shallow-renderer'
warn Unable to resolve module 'regenerator-runtime'
warn Unable to resolve module 'scheduler'
warn Unable to resolve module 'stacktrace-parser'
warn Unable to resolve module 'use-subscription'
warn Unable to resolve module 'whatwg-fetch'
warn Unable to resolve module 'ws'
warn Unable to resolve module 'react-native-codegen'
```

### Affected Package

@rnx-kit/metro-resolver-symlinks

### Version

0.1.19

### Which platforms are you seeing this issue on?

- [ ] Android
- [ ] iOS
- [ ] macOS
- [ ] Windows

### System Information

```true
System:
    OS: macOS 12.4
    CPU: (10) arm64 Apple M1 Max
    Memory: 14.19 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.0 - /usr/bin/node
    Yarn: 1.22.18 - /usr/bin/yarn
    npm: 8.3.1 - /usr/bin/npm
    Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8309675
    Xcode: 13.4/13F17a - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.14.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: ^0.68.0-0 => 0.68.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

pnpm version: `6.32.2`
```

### Steps to Reproduce

I made a test repo that I managed to reproduce the issue: https://github.com/jbarzegar/rnx-kit-symlink-resolver-test

Here's the steps I used to setup the test repo:

- ensure pnpm is installed
- create a project `pnpx react-native init <Name>`
- remove yarn.lock & node modules: `rm -rf yarn.lock node_modules`
- reinstall with `pnpm`: `pnpm install`
- setup dep-check according to rnx's [getting started guide](https://microsoft.github.io/rnx-kit/docs/guides/getting-started)
- once dep changes have been changed run `pnpm install`
- install `metro-config` and `metro-resolver-symlinks`: `pnpm add -D @rnx-kit/{metro-config,metro-resolver-symlinks}`
- Attempt to start the dev server via `pnpm start`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tido64** [comment]
Hi @jbarzegar, thanks for filing this detailed issue with a repro! I've just submitted a fix. Let me know how it works for you.

**Comment by jbarzegar** [comment]
Hi @tido64, no problem I have checked out the fixed branch and can confirm the issue has been fixed using the [test repo]( https://github.com/jbarzegar/rnx-kit-symlink-resolver-test) I supplied in the previous post. Thank you very much for your quick reply and fix! ❤️ 

I'm going to close this issue thanks again
