### ISSUE TITLE
metro-resolver-symlinks + pnpm + rn non semver dep: unable to resolve module react-native

### ISSUE THREAD

**Issue by danilobuerger** [microsoft/rnx-kit#1744]
### What happened?

When using @rnx-kit/metro-resolver-symlinks with pnpm and a rn non semver dep the following error occurs on bundling:

```
error: Error: Unable to resolve module react-native from /.../index.js: react-native could not be found within the project or in these directories:
  node_modules
  /.../node_modules/.pnpm/github.com+facebook+react-native@72e1eda0736d34d027e4d4b1c3cace529ab5dcf3_react@17.0.2/node_modules/react-native
    at ModuleResolver.resolveDependency (/.../node_modules/.pnpm/metro@0.67.0/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:158:15)
    at DependencyGraph.resolveDependency (/.../node_modules/.pnpm/metro@0.67.0/node_modules/metro/src/node-haste/DependencyGraph.js:231:43)
    at Object.resolve (/.../node_modules/.pnpm/metro@0.67.0/node_modules/metro/src/lib/transformHelpers.js:129:24)
    at resolve (/.../node_modules/.pnpm/metro@0.67.0/node_modules/metro/src/DeltaBundler/traverseDependencies.js:396:33)
    at /.../node_modules/.pnpm/metro@0.67.0/node_modules/metro/src/DeltaBundler/traverseDependencies.js:412:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (/.../node_modules/.pnpm/metro@0.67.0/node_modules/metro/src/DeltaBundler/traverseDependencies.js:411:33)
    at processModule (/.../node_modules/.pnpm/metro@0.67.0/node_modules/metro/src/DeltaBundler/traverseDependencies.js:140:31)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### Affected Package

@rnx-kit/metro-resolver-symlinks

### Version

0.1.21

### Which platforms are you seeing this issue on?

- [ ] Android
- [X] iOS
- [ ] macOS
- [ ] Windows

### System Information

```true
System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1
    Memory: 94.52 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /Users/danilo/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.0 => 0.68.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to Reproduce

Inside package.json set a rn dep:

```
{
  "dependencies": {
    "react-native": "facebook/react-native#0.68-stable"
  }
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tido64** [comment]
Thanks for reporting this, @danilobuerger! Does regular semver work for you? What does your Metro config look like?

Can you create a new repo where this issue can be reproduced for us?

**Comment by danilobuerger** [comment]
@tido yes, regular semver works. 
Repo is at https://github.com/danilobuerger/repo_rnx-kit_1744
Its basically `npx react-native init rnxtest --version 0.68.0` modified to use rnx-kit metro config / symlink as described on the website and using a non semver rn dep.

**Comment by tido64** [comment]
I think I've figured out why this breaks. I just need to make sure my test doesn't break on Windows. It would also be great if you could verify it on your machine.

**Comment by danilobuerger** [comment]
Works, thanks!
