### ISSUE TITLE
metro-resolver-symlinks + pnpm: unable to resolve files in module

### ISSUE THREAD

**Issue by danilobuerger** [microsoft/rnx-kit#1752]
### What happened?

As a follow up to #1744 with the same repo at https://github.com/danilobuerger/repo_rnx-kit_1744 after installing a dependency some files from that module can't be resolved. I am using `intl-pluralrules` as an example, but this happens with other dependencies too:

```
error: Error: Unable to resolve module ./factory from /.../node_modules/.pnpm/intl-pluralrules@1.3.1/node_modules/intl-pluralrules/plural-rules.js: ./factory could not be found within the project or in these directories:
  node_modules/.pnpm/intl-pluralrules@1.3.1/node_modules
  node_modules/.pnpm/node_modules
  node_modules
  1 | 'use strict';
  2 |
> 3 | var getPluralRules = require('./factory');
    |                               ^
  4 | var PseudoNumberFormat = require('./pseudo-number-format');
  5 |
  6 | function _interopDefaultLegacy (e) { return e && typeof e === 'object' && 'default' in e ? e : { 'default': e }; }
    at ModuleResolver.resolveDependency (/.../node_modules/.pnpm/metro@0.67.0/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:158:15)
    at DependencyGraph.resolveDependency (/.../node_modules/.pnpm/metro@0.67.0/node_modules/metro/src/node-haste/DependencyGraph.js:231:43)
    at Object.resolve (/.../node_modules/.pnpm/metro@0.67.0/node_modules/metro/src/lib/transformHelpers.js:129:24)
    at resolve (/.../node_modules/.pnpm/metro@0.67.0/node_modules/metro/src/DeltaBundler/traverseDependencies.js:396:33)
    at /.../node_modules/.pnpm/metro@0.67.0/node_modules/metro/src/DeltaBundler/traverseDependencies.js:412:26
    at Array.reduce (<anonymous>)
    at resolveDependencies (/.../node_modules/.pnpm/metro@0.67.0/node_modules/metro/src/DeltaBundler/traverseDependencies.js:411:33)
    at processModule (/.../node_modules/.pnpm/metro@0.67.0/node_modules/metro/src/DeltaBundler/traverseDependencies.js:140:31)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async addDependency (/.../node_modules/.pnpm/metro@0.67.0/node_modules/metro/src/DeltaBundler/traverseDependencies.js:230:18)
```

However, the file is there:

```
❯ ls -al node_modules/.pnpm/intl-pluralrules@1.3.1/node_modules/intl-pluralrules
total 160
drwxr-xr-x  13 danilo  staff    416 Jul 18 19:58 .
drwxr-xr-x   3 danilo  staff     96 Jul 18 19:58 ..
-rw-r--r--   3 danilo  staff    752 Jul 13 17:31 LICENSE
-rw-r--r--   3 danilo  staff   3327 Jul 13 17:31 README.md
-rw-r--r--   3 danilo  staff    364 Jul 13 17:31 factory.d.ts
-rw-r--r--   3 danilo  staff   5716 Jul 13 17:31 factory.js
-rw-r--r--   3 danilo  staff   5706 Jul 13 17:31 factory.mjs
-rw-r--r--   3 danilo  staff   1933 Jul 13 17:31 package.json
-rw-r--r--   3 danilo  staff     81 Jul 13 17:31 plural-rules.d.ts
-rw-r--r--   3 danilo  staff  32581 Jul 13 17:31 plural-rules.js
-rw-r--r--   3 danilo  staff   1075 Jul 13 17:31 polyfill.js
-rw-r--r--   3 danilo  staff     84 Jul 13 17:31 pseudo-number-format.d.ts
-rw-r--r--   3 danilo  staff   2633 Jul 13 17:31 pseudo-number-format.js
```

### Affected Package

@rnx-kit/metro-resolver-symlinks

### Version

0.1.21

### Which platforms are you seeing this issue on?

- [ ] Android
- [X] iOS
- [ ] macOS
- [ ] Windows

### System Information

```true
System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1
    Memory: 71.11 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /Users/danilo/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8193401
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.0 => 0.68.0 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to Reproduce

See https://github.com/danilobuerger/repo_rnx-kit_1744

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tido64** [comment]
This one seems related to CJS vs ESM. Try adding `mjs` as a source extension:

```diff
diff --git a/metro.config.js b/metro.config.js
index d9d9eff..7f14b27 100644
--- a/metro.config.js
+++ b/metro.config.js
@@ -10,6 +10,7 @@ const MetroSymlinksResolver = require('@rnx-kit/metro-resolver-symlinks');

 module.exports = makeMetroConfig({
   resolver: {
+    sourceExts: ['mjs', 'js', 'json', 'ts', 'tsx'],
     resolveRequest: MetroSymlinksResolver(),
   },
   transformer: {
```

**Comment by danilobuerger** [comment]
That seems to fix it. I wonder though why its necessary as when using yarn and **not** rnx-kit, it works without adding it mjs to sourceExts.

**Comment by afoxman** [comment]
@tido64 @danilobuerger Is there a followup fix needed in rnx-kit? Seems like the presence of "module" requires some additional changes to make things work like yarn does today.

**Comment by danilobuerger** [comment]
@afoxman Metro recently changed its behavior by including cjs and mjs by default (see https://github.com/facebook/metro/commit/c1c6d9c09fa92aa2ba71d803fdfa480e4dbb6a51). I think rnx-kit should match this, which I think should resolve this error?

**Comment by tido64** [comment]
> @tido64 How about adding something like this in our standard config?
> 
> ```js
> sourceExts: [...existingDefaultsHere, "mjs", "cjs"],
> ```

I've been looking into this a bit: It's not as simple as adding extra extensions here. I'm getting to the conoclusion that we probably shouldn't have added `module` in the first place. The issue is that once you go from an ESM module to CJS, you should only import CJS after that. However, Metro doesn't support this natively. It will always pick `module` when it should be using `main`. Removing `module` essentially means that tree-shaking will be a lot less efficient.

**Comment by danilobuerger** [comment]
Thanks @tido64
