### ISSUE TITLE
react-native-dotenv setup breaks rnx-cli start command

### ISSUE THREAD

**Issue by owonwo** [microsoft/rnx-kit#1880]
### What happened?

I'm getting an error whenever I run:

```bash
 npx react-native rnx-start
```
I'm using react-native-dotenv to inject environment variables into the app from an .env file. I think that's what causing the error. 

Please see `babel.config.js`:
```js
module.exports = {
  presets: ['@rnx-kit/babel-preset-metro-react-native'],
  plugins: [
    [
      'module:react-native-dotenv',
      {
        moduleName: '@env',
        path: '.env',
        blocklist: null,
        allowlist: null,
        safe: false,
        allowUndefined: true,
        verbose: false,
      },
    ],
  ],
};
```

and the error:

```bash

error: Error: Invalid package reference: "@env"
    at parsePackageRef (/Users/owonwo/Documents/projects/products/envoi/customer/node_modules/@rnx-kit/tools-node/lib/package.js:50:19)
    at parseModuleRef (/Users/owonwo/Documents/projects/products/envoi/customer/node_modules/@rnx-kit/tools-node/lib/module.js:22:47)
    at resolveModuleName (/Users/owonwo/Documents/projects/products/envoi/customer/node_modules/@rnx-kit/typescript-react-native-resolver/lib/host.js:77:55)
    at resolveModuleNames (/Users/owonwo/Documents/projects/products/envoi/customer/node_modules/@rnx-kit/typescript-react-native-resolver/lib/host.js:120:22)
    at actualResolveModuleNamesWorker (/Users/owonwo/Documents/projects/products/envoi/customer/node_modules/typescript/lib/typescript.js:116656:153)
    at resolveModuleNamesWorker (/Users/owonwo/Documents/projects/products/envoi/customer/node_modules/typescript/lib/typescript.js:116959:26)
    at resolveModuleNamesReusingOldState (/Users/owonwo/Documents/projects/products/envoi/customer/node_modules/typescript/lib/typescript.js:117057:24)
    at processImportedModules (/Users/owonwo/Documents/projects/products/envoi/customer/node_modules/typescript/lib/typescript.js:118567:35)
    at findSourceFileWorker (/Users/owonwo/Documents/projects/products/envoi/customer/node_modules/typescript/lib/typescript.js:118347:17)
    at findSourceFile (/Users/owonwo/Documents/projects/products/envoi/customer/node_modules/typescript/lib/typescript.js:118196:26)
```

### Affected Package

@rnx-kit/cli

### Version

0.14.3

### Which platforms are you seeing this issue on?

- [X] Android
- [X] iOS
- [ ] macOS
- [ ] Windows

### System Information

```true
System:
    OS: macOS 12.2
    CPU: (8) x64 Apple M1
    Memory: 39.05 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.19.1 - ~/.nvm/versions/node/v14.19.1/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.16 - ~/.nvm/versions/node/v14.19.1/bin/npm
    Watchman: 2022.03.21.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK:
      API Levels: 29, 30, 31
      Build Tools: 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0
      System Images: android-29 | Intel x86 Atom_64, android-31 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
    Xcode: 13.4.1/13F100 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: ^0.65.0 => 0.65.1 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to Reproduce

I simply ran  `npx react-native rnx-start` after installing and setting up `react-native-dotenv` package

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by afoxman** [comment]
Hi @owonwo! It looks like TypeScript is getting confused by `moduleName` being set to `@env`. And since we've integrated TypeScript with Metro, you are seeing errors from our CLI.

On the `react-native-dotenv` GitHub docs, there is a section for [using the library with TypeScript](https://github.com/goatandsheep/react-native-dotenv#option-1-easy-mode). Can you give that a shot and let us know how it goes?

**Comment by owonwo** [comment]
Thanks @afoxman I had to rename all imports from `@env` to `react-native-dotenv` and also changed the `moduleName` property to `react-native-dotenv`. That fixed the build error.
