### ISSUE TITLE
win32 and macOS should be included the list of available platforms

### ISSUE THREAD

**Issue by lyzhan7** [microsoft/rnx-kit#1955]
### What happened?

Currently all our jest tests run on Android. We want to be able to run them on win32. When we try to configure the test to run on win32, we get an error that the only available platforms are iOS and Android. 

```
ERR! [@fluentui-react-native/win32-theme test] ERROR DETECTED
ERR! started
ERR! hash: 6c9d8d460cd73da8f083ae615393c0efa630f1da, cache hit? false
ERR! Running /var/folders/d2/s15t9v9s09392vpbfv_h78dw0000gn/T/yarn--1666295648841-0.6314284952155775/yarn run test -- -u
warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.
$ fluentui-scripts jest -u
ERR! [12:54:47 PM] ■ started 'jest'
ERR! [12:54:47 PM] ■ Running Jest
ERR! [12:54:47 PM] ■ /usr/local/bin/node "/Users/lyzhan/Documents/GitHub/fluentui-react-native/node_modules/jest/bin/jest.js" --config "/Users/lyzhan/Documents/GitHub/fluentui-react-native/packages/theming/win32-theme/jest.config.js" --colors --updateSnapshot
ERR! Error: 'win32' was not found among available platforms: ios, android
ERR!     at getTargetPlatform (/Users/lyzhan/Documents/GitHub/fluentui-react-native/node_modules/@rnx-kit/jest-preset/src/index.js:91:11)
ERR!     at module.exports (/Users/lyzhan/Documents/GitHub/fluentui-react-native/node_modules/@rnx-kit/jest-preset/src/index.js:198:42)
ERR!     at configureReactNativeJest (/Users/lyzhan/Documents/GitHub/fluentui-react-native/scripts/lib/configs/configureJest.js:41:38)
ERR!     at Object.<anonymous> (/Users/lyzhan/Documents/GitHub/fluentui-react-native/packages/theming/win32-theme/jest.config.js:2:18)
ERR!     at Module._compile (internal/modules/cjs/loader.js:1085:14)
ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
ERR!     at Module.load (internal/modules/cjs/loader.js:950:32)
ERR!     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
ERR!     at Module.require (internal/modules/cjs/loader.js:974:19)
ERR!     at require (internal/modules/cjs/helpers.js:101:18)
ERR! [12:54:54 PM] x Error detected while running 'jest'
ERR! [12:54:54 PM] x ------------------------------------
ERR! [12:54:54 PM] x Error: Command failed: /usr/local/bin/node /Users/lyzhan/Documents/GitHub/fluentui-react-native/node_modules/jest/bin/jest.js --config /Users/lyzhan/Documents/GitHub/fluentui-react-native/packages/theming/win32-theme/jest.config.js --colors --updateSnapshot
ERR!     at ChildProcess.<anonymous> (/Users/lyzhan/Documents/GitHub/fluentui-react-native/node_modules/just-scripts-utils/lib/exec.js:93:31)
ERR!     at ChildProcess.emit (events.js:400:28)
ERR!     at ChildProcess.emit (domain.js:537:15)
ERR!     at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)
ERR!     at Process.callbackTrampoline (internal/async_hooks.js:130:17)
ERR! [12:54:54 PM] x ------------------------------------
ERR! [12:54:54 PM] x Error previously detected. See above for error messages.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERR! failed
info ----------------------------------------------
info Took a total of 44.45s to complete
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Affected Package

@rnx-kit/jest-preset

### Version

0.1.11

### Which platforms are you seeing this issue on?

- [ ] Android
- [ ] iOS
- [X] macOS
- [X] Windows

### System Information

```true
info Fetching system and libraries information...
System:
    OS: macOS 12.6
    CPU: (8) x64 Apple M1
    Memory: 18.80 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.19.1 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 6.14.16 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 16.0, macOS 12.3, tvOS 16.0, watchOS 9.0
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8609683
    Xcode: 14.0/14A309 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Steps to Reproduce

In our jest.config file, we called jest-preset with 'win32' instead of 'android' and then ran the test.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tido64** [comment]
Hi @lyzhan7, platform availability is determined by `react-native config`. You need to at least have `@office-iss/react-native-win32` declared under `devDependencies` for the `win32` platform to be detected. Can you try adding it to `@fluentui-react-native/win32-theme` and run Jest again?
