### ISSUE TITLE
TypeScript plugin doesn't respect project references

### ISSUE THREAD

**Issue by aspirisen** [microsoft/rnx-kit#3307]
### What happened?

I have a monorepo, each package has its own `paths` property. When I run metro I see an error like that 

```
error: Error: Invalid package reference: "@/responsive/useResponsive"
    at parsePackageRef (/Users/me/project/node_modules/@rnx-kit/tools-node/src/package.ts:29:15)
    at parseModuleRef (/Users/me/project/node_modules/@rnx-kit/tools-node/src/module.ts:36:48)
    at isPackageRef (/Users/me/project/node_modules/@rnx-kit/metro-plugin-typescript/src/resolver.ts:6:25)
    at resolveModuleName (/Users/me/project/node_modules/@rnx-kit/metro-plugin-typescript/src/resolver.ts:32:31)
    at resolveModuleNameLiterals (/Users/me/project/node_modules/@rnx-kit/metro-plugin-typescript/src/resolver.ts:113:28)
    at Object.host.resolveModuleNameLiterals (/Users/me/project/node_modules/@rnx-kit/metro-plugin-typescript/src/host.ts:98:34)
    at resolveModuleNamesWorker (/Users/me/project/node_modules/typescript/lib/typescript.js:124573:20)
    at resolveModuleNamesReusingOldState (/Users/me/project/node_modules/typescript/lib/typescript.js:124659:14)
    at processImportedModules (/Users/me/project/node_modules/typescript/lib/typescript.js:126176:118)
    at findSourceFileWorker (/Users/me/project/node_modules/typescript/lib/typescript.js:125954:7)
  ```
  
  Where `@/responsive/useResponsive` is an import in a package with the following tsconfig
```
"composite": true,
"baseUrl": ".",
"paths": {
    "@/*": ["./*"]
},
```

P.S. I use just `@rnx-kit/metro-plugin-typescript` package in metro config, without any other `@rnx-kit/*` package.

### Affected Package

@rnx-kit/metro-plugin-typescript

### Version

^0.4.4

### Which platforms are you seeing this issue on?

- [ ] Android
- [X] iOS
- [ ] macOS
- [ ] Windows

### System Information

```true
System:
  OS: macOS 14.6.1
  CPU: (10) arm64 Apple M1 Max
  Memory: 3.68 GB / 64.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 22.3.0
    path: ~/.nvm/versions/node/v22.3.0/bin/node
  Yarn:
    version: 1.22.22
    path: ~/.nvm/versions/node/v22.3.0/bin/yarn
  npm:
    version: 10.8.1
    path: ~/.nvm/versions/node/v22.3.0/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.15.2
    path: /Users/dima/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.5
      - iOS 17.5
      - macOS 14.5
      - tvOS 17.5
      - visionOS 1.2
      - watchOS 10.5
  Android SDK: Not Found
IDEs:
  Android Studio: 2023.3 AI-233.14808.21.2331.11842104
  Xcode:
    version: 15.4/15F31d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.12
    path: /usr/bin/javac
  Ruby:
    version: 2.7.6
    path: /Users/dima/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react: Not Found
  react-native: Not Found
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: Not found
  newArchEnabled: Not found
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Steps to Reproduce

Set-up monorepo, create i.e. ui-kit package
Inside ui-kit  tsconfig add these props
```
"composite": true,
"baseUrl": ".",
"paths": {
    "@/*": ["./*"]
},
```
Inside ui-kit package add some import using the path alias
Inside your app import the file

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tido64** [comment]
Thanks for the report! I've submitted a fix.
